export const SOCIAL_REGISTER_REQUEST = 'Account/SOCIAL_REGISTER_REQUEST';
export const SOCIAL_REGISTER_SUCCESS = 'Account/SOCIAL_REGISTER_SUCCESS';
export const SOCIAL_REGISTER_FAILED = 'Account/SOCIAL_REGISTER_FAILED';
