export const SOCIAL_REGISTER_REQUEST = 'Account/SOCIAL_REGISTER_REQUEST';
export const SOCIAL_REGISTER_SUCCESS = 'Account/SOCIAL_REGISTER_SUCCESS';
export const SOCIAL_REGISTER_FAILED = 'Account/SOCIAL_REGISTER_FAILED';

export const SOCIAL_LOGIN_REQUEST = 'Account/SOCIAL_LOGIN_REQUEST';
export const SOCIAL_LOGIN_SUCCESS = 'Account/SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_FAILED = 'Account/SOCIAL_LOGIN_FAILED';

export const GET_USER_DETAIL_REQUEST = 'Account/GET_USER_DETAIL_REQUEST';
export const GET_USER_DETAIL_SUCCESS = 'Account/GET_USER_DETAIL_SUCCESS';
export const GET_USER_DETAIL_FAILED = 'Account/GET_USER_DETAIL_FAILED';
