export const SOCIAL_REGISTER_REQUEST = 'Account/SOCIAL_REGISTER_REQUEST';
export const SOCIAL_REGISTER_SUCCESS = 'Account/SOCIAL_REGISTER_SUCCESS';
export const SOCIAL_REGISTER_FAILED = 'Account/SOCIAL_REGISTER_FAILED';

export const SOCIAL_LOGIN_REQUEST = 'Account/SOCIAL_LOGIN_REQUEST';
export const SOCIAL_LOGIN_SUCCESS = 'Account/SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_FAILED = 'Account/SOCIAL_LOGIN_FAILED';
