export const GET_ROOM_PARTICIPATED_USERS_REQUEST =
  'GET_ROOM_PARTICIPATED_USERS_REQUEST';
export const GET_ROOM_PARTICIPATED_USERS_SUCCESS =
  'GET_ROOM_PARTICIPATED_USERS_SUCCESS';
export const GET_ROOM_PARTICIPATED_USERS_FAILED =
  ' GET_ROOM_PARTICIPATED_USERS_FAILED';
