export const GET_ROOM_PARTICIPATED_USERS_REQUEST =
  'GET_ROOM_PARTICIPATED_USERS_REQUEST';
export const GET_ROOM_PARTICIPATED_USERS_SUCCESS =
  'GET_ROOM_PARTICIPATED_USERS_SUCCESS';
export const GET_ROOM_PARTICIPATED_USERS_FAILED =
  ' GET_ROOM_PARTICIPATED_USERS_FAILED';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';
