export const GET_ROOM_LIST_REQUEST = 'Rooms/GET_ROOM_LIST_REQUEST';
export const GET_ROOM_LIST_SUCCESS = 'Rooms/GET_ROOM_LIST_SUCCESS';
export const GET_ROOM_LIST_FAILED = 'Rooms/GET_ROOM_LIST_FAILED';

export const GET_ROOMS_COUNT_REQUEST = 'GET_ROOMS_COUNT_REQUEST';
export const GET_ROOMS_COUNT_SUCCESS = 'GET_ROOMS_COUNT_SUCCESS';
export const GET_ROOMS_COUNT_FAILED = 'GET_ROOMS_COUNT_FAILED';
