export const GET_ROOM_LIST_REQUEST = 'Rooms/GET_ROOM_LIST_REQUEST';
export const GET_ROOM_LIST_SUCCESS = 'Rooms/GET_ROOM_LIST_SUCCESS';
export const GET_ROOM_LIST_FAILED = 'Rooms/GET_ROOM_LIST_FAILED';
